### ISSUE TITLE
npm start not working 

### ISSUE THREAD

**Issue by astania** [learn-co-curriculum/react-hooks-state-arrays#6] opened 2022-01-25 19:14 UTC
This could be an issue on my end, but after entering npm install and then npm start, the browser tab opened, but it shows 

"This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED"

**The terminal error is:**

"Compiled with warnings.

src/components/SpicyFoodList.js
  Line 5:17:  'setFoods' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

/home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/watcherManager.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/watchpack.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/webpack/lib/webpack.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/react-scripts/scripts/start.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/watcherManager.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/watchpack.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/webpack/lib/webpack.js
- /home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/react-scripts/scripts/start.js

    at Object.<anonymous> (/home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/annae/Development/code/Mod2/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)"

**Comment by lizbur10** [comment] 2022-01-27 14:42
Hi @astania ! Sorry to hear you ran into problems!

I am not able to reproduce the error on my machine which suggests the issue may be with your local environment setup. I'm going to go ahead and close this issue but feel free to reopen it if you believe the lesson needs to be updated.

If you still need assistance with this error, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team. 💙

**Closed as completed by lizbur10** 2022-01-27 14:42 UTC
