### ISSUE TITLE
lesson doesn't compile in React

### ISSUE THREAD

**Issue by readlang** [learn-co-curriculum/react-hooks-state-arrays#5] opened 2021-11-30 20:25 UTC
### Canvas Link

https://learning.flatironschool.com/courses/4600/assignments/147230?module_item_id=310612

### Concern

This lesson won't compile in React.  At least on my machine, although I have had zero problems running all the other lessons in React.  When I run "npm start" it gives an error.  Again, I've had no problems with other lessons.
NPM says it can't find module "chokidar".  Not sure if there are other issues.

**Comment by lizbur10** [comment] 2021-12-02 14:52
Hi @readlang ! Sorry to hear you're running into problems!

I am not able to recreate this issue - npm start works fine for me. This suggests that the problem is with your local environment rather than the lab itself, so I'm going to go ahead and close this issue. If you still believe there is a curriculum issue, feel free to reopen the issue and we'll take another look.

One thing you can try if you haven't yet is installing chokidar yourself with `npm install chokidar`. If that doesn't work, I recommend that you reach out to your instructor for help or use the Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Thanks for contributing to the Flatiron School curriculum 💙

**Closed as completed by lizbur10** 2021-12-02 14:52 UTC
Labels: se curriculum
